### ISSUE TITLE
Too many tiles for the Information Resource's Creation card

### ISSUE THREAD

**Issue by chiatt** [fargeo/afrh#33]
The Creation card in the Information Resource model has a cardinality of 1. However, for many instances there are multiple tiles. These need to be consolidated into a single tile. See this resource instance as an example: http://localhost:8000/resource/a2f91e42-20e8-492c-a9a8-50bba0801f04#

**Comment by ryan86** [comment]
Combined creator cards, changed Creator Node from resource-instance to string because appellations in source data (string datatype) did not match up with actor/organization resource instance names in target.

**Comment by mradamcox** [comment]
Had to change the Creation card to accept multiple values, then the business data loaded without error. After that, got an error from multiple spatial nodegroup tiles.

In the business_data their were often two tiles for this nodegroup: one that held the geom and had an empty note and one that held the note and had an empty geom. Manually combined these rather than allowing multiple tiles for this nodegroup. However, the cardinality error still occurred, even after triple-checking that there was only a single tile for that nodegroup per resource. Ultimately, I just set the card to accept multiple node groups. I wasn't deleting all resources in between loads, so maybe there were still orphan nodes in the db (I was importing using `-ow overwrite`)
